spring:
  application:
    name: focus

  datasource:
    url: jdbc:postgresql://localhost:5432/focus_avatar
    username: focus_user
    password: focus_password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
      show-sql: true

    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  common:
    key: ${JWT_SECRET}


kakao:
  oauth:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/oauth/kakao
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

focus:
  metadata:
    redis:
      key-template: broadcast:{broadcast_id}:meta:{pts_us}
      ttl-seconds: 60

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
