spring:
  application:
    name: focus

  datasource:
    url: jdbc:postgresql://localhost:5432/focus_avatar
    username: focus_user
    password: focus_password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
      show-sql: true

    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace