DROP TABLE IF EXISTS tracking_session;
DROP TABLE IF EXISTS identity_mapping;
DROP TABLE IF EXISTS broadcast;
DROP TABLE IF EXISTS avatar;
DROP TABLE IF EXISTS member;

CREATE TABLE member (
                        member_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email           VARCHAR(100) NOT NULL UNIQUE,
                        nickname        VARCHAR(50) NOT NULL,
                        role            VARCHAR(20) DEFAULT 'USER',

                        face_embedding  JSONB,

                        created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE avatar (
                        avatar_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        avatar_name     VARCHAR(50),
                        s3_object_key   VARCHAR(255) NOT NULL,
                        thumbnail_url   VARCHAR(255),

                        gender          VARCHAR(10),
                        age_group       VARCHAR(20),
                        ethnicity       VARCHAR(20),
--                         body_type       VARCHAR(20), (일단 생략)
                        skeleton_type   VARCHAR(50) DEFAULT 'GAME_ENGINE',

                        is_active       BOOLEAN DEFAULT TRUE
);

CREATE TABLE broadcast (
                           broadcast_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           member_id       BIGINT NOT NULL,

                           stream_key      VARCHAR(100) NOT NULL UNIQUE,
                           title           VARCHAR(200),
                           status          VARCHAR(20) DEFAULT 'READY',
                           hls_url         VARCHAR(255),

                           started_at      TIMESTAMP,
                           ended_at        TIMESTAMP,

                           CONSTRAINT fk_broadcast_member FOREIGN KEY (member_id) REFERENCES member(member_id)
);

CREATE TABLE tracking_session (
                                  tracking_session_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  broadcast_id    BIGINT NOT NULL,
                                  tracking_id     VARCHAR(100) NOT NULL,
                                  avatar_id       BIGINT NOT NULL,

                                  first_seen_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  last_seen_at    TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

                                  is_active       BOOLEAN DEFAULT TRUE,

                                  CONSTRAINT fk_mapping_broadcast FOREIGN KEY (broadcast_id) REFERENCES broadcast(broadcast_id),
                                  CONSTRAINT fk_mapping_avatar FOREIGN KEY (avatar_id) REFERENCES avatar(avatar_id)
);

CREATE INDEX idx_tracking_session_lookup ON tracking_session (broadcast_id, tracking_id);