# -*- coding: utf-8 -*-
"""reenact

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYWPjSCuW0jr9Y-mdYTp-S4bIZT-ANqG
"""

#환경설정
!pip -q install torch opencv-python-headless scipy

# Commented out IPython magic to ensure Python compatibility.
# 깃클론(파일 가져오는 용)
# %cd /content
!git clone -b main https://github.com/KMU-FOCUS/focus-avatar.git
# %cd /content/focus-avatar/project/

#(메타데이터경로,영상경로,출력영상경로,소스아바타폴더경로)
!python -m reenactment.reenact_cli \
  --metadata /content/meta.json \
  --video /content/metadata.mp4 \
  --output-video /content/output_reenact.mp4 \
  --avatar-bank-dir /content/focus-avatar/project/avatar_bank