# -*- coding: utf-8 -*-
"""source.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2_XN5jJLHARrFu26pEXrzw4bZ3OeLD4
"""

#모델로드
!git clone https://github.com/quic/ai-hub-models.git /content/ai-hub-models

#환경설정
!pip install -q qai-hub-models mediapipe opencv-python scipy onnxruntime-gpu

# Commented out IPython magic to ensure Python compatibility.
#깃 클론
# %cd /content
!git clone -b main https://github.com/KMU-FOCUS/focus-avatar.git
# %cd /content/focus-avatar/project/

# Commented out IPython magic to ensure Python compatibility.
#아바타 전처리
# %cd /content/focus-avatar/project
#경로수정(이미지 입력 폴더, 출력경로)
!python3 -m source_avatar.source_avatar_cli \
  --source-dir /content/avatar \
  --output-dir /content/avatar_bank

import os
import subprocess

root = "/content/avatar"    #아바타 png 폴더가 들어있는 폴더경로
out_dir = "/content/avatar_bank" #출력 경로
prefix = "avatar"
start_num = 7   #아바타id 시작 번호

os.makedirs(out_dir, exist_ok=True)

folders = sorted(
    [d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))],
    key=lambda x: int(x) if x.isdigit() else x
)

for i, folder in enumerate(folders, start=start_num):
    src_dir = os.path.join(root, folder)
    front_path = None

    for ext in [".png", ".jpg", ".jpeg", ".webp"]:
        candidate = os.path.join(src_dir, f"front{ext}")
        if os.path.exists(candidate):
            front_path = candidate
            break

    if front_path is None:
        print(f"skip: {src_dir} (front 이미지 없음)")
        continue

    subprocess.run([
        "python", "-m", "source_avatar.source_avatar_cli",
        "--source-dir", src_dir,
        "--output-dir", out_dir,
    ], check=True)

    old_path = os.path.join(out_dir, folder)
    new_name = f"{prefix}_{i:03d}"
    new_path = os.path.join(out_dir, new_name)

    if os.path.exists(old_path):
        os.rename(old_path, new_path)
        print(f"{folder} -> {new_name}")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!zip -r avatar_bank.zip avatar_bank